data:
  type: mnist
  train_dir: data/MNIST
  deterministic: True
  img_size: 32
  nlabels: 10
condition:
  num_k: 15
generator:
  name: dcgan_shallow
  conditioning: embedding_add
  kwargs:
    nc: 1
    embed_norm: False
    placeholder: None
discriminator:
  name: dcgan_shallow
  conditioning: mask
  kwargs:
    nc: 1
    placeholder: None
encoder:
  name: dcgan_shallow
  kwargs:
    nc: 1
    placeholder: None
multi_gauss:
  embed_dim: 15
  fix_mean: False
  sigma_scalor: 1.0
  dim_reduce: True
  reduce_ratio: 0.95
z_dist:
  type: gauss
  dim: 256
clusterer:
  name: crp
  nimgs: 25000
  kwargs: 
    placeholder: None
    epoch_1: 5
    epoch_2: 5
training:
  stage: crp
  batch_size: 64
  n_init: 2400000
  n_q: 64000
  n_gd: 600000
  crp_epoch: 40
  out_dir: output/mnist/crp_reduce
  gan_type: standard
  reg_type: real
  reg_param: 10.
  encoder_type: l2
  encoder_param: [0.1, 0.0]
  take_model_average: false
pretrained: {'model': 'output/mnist/initialization/chkpts/model.pt'}