data:
  type: mnist
  train_dir: data/MNIST
  deterministic: True
  img_size: 32
  nlabels: 10
condition:
  num_k: 15
generator:
  name: dcgan_shallow
  conditioning: embedding_add
  kwargs:
    nc: 1
    embed_norm: False
    placeholder: None
discriminator:
  name: dcgan_shallow
  conditioning: unconditional
  kwargs:
    nc: 1
    placeholder: None
encoder:
  name: dcgan_shallow
  kwargs:
    nc: 1
    placeholder: None
multi_gauss:
  embed_dim: 15
  fix_mean: False
  sigma_scalor: 1.0
  dim_reduce: False
  reduce_ratio: 0.95
z_dist:
  type: gauss
  dim: 256
clusterer:
  name: random_labels
  kwargs: 
    placeholder: None
training:
  stage: initialization
  batch_size: 64
  n_init: 2400000
  n_q: 64000
  n_gd: 600000
  crp_epoch: 40
  sample_stop_epoch: -1
  out_dir: output/mnist/initialization
  gan_type: standard
  reg_type: real
  reg_param: 10.
  encoder_type: l2
  encoder_param: [0.1, 0.0]
  ntest: 128
  nworkers: 72
  take_model_average: true
  model_average_beta: 0.999
  monitoring: tensorboard
  optimizer: adam
  lr_g: 0.0001
  lr_d: 0.0001
  lr_q: 0.0001
  beta1: 0.0
  beta2: 0.99
pretrained: {}